### PR TITLE
Allow to set tagName with decorator

### PR DESCRIPTION
**Pull request by chenjiahan**
``` javascript
import Vue from 'vue'
import Component from 'vue-class-component'

@Component({
  name: 'app'
})
export default class App extends Vue {
  public name: string;
}
```

### CODE REVIEW

**Comment by ktsn** [comment]
Why don't you use `vm.$options.name`? What is the use case of this?

**Comment by chenjiahan** [comment]
This is used for registering a global component.

``` javascript
import App from './app';

Vue.component(App.name, app);
```

**Comment by ktsn** [comment]
I think this feature should be in core `extend` method because vue-class-component intends to just wrap `Vue.extend` api and provide class like syntax.
Would you mind to send PR to [core repo](https://github.com/vuejs/vue)?

**Comment by HerringtonDarkholme** [comment]
Isn't `App.options.name` enough? I wonder.

**Comment by chenjiahan** [comment]
`App.options.name` is a little weird, I'm trying to find a more elegant solution.

**Comment by ktsn** [comment]
In my understanding, `App.options` is officially undocumented api but it can fill the use case.
If you want safer solution, you should request api to core as I mentioned.

**Pull request closed without merging**
