### PR TITLE
add property decorators

### PR DESCRIPTION
**Pull request by kaorun343**
Hi.

As a lot of the developers use TS  and Vue together, I think `vue-class-component` and `vue-property-decorator` should be unified.

So, I would like to add some decorators in my repository to this repository.

### CODE REVIEW

**Comment by l5x** [comment]
`vue-property-decorator` depends on `reflect-metadata` which offloads the cost of developer convenience to the client. I would argue that there are many that are happy with just `vue-class-component`. It would be nice to retain the choice the developers have with the two modules, especially that `vue-class-component` defines a way to extend its functionality.

**Comment by ktsn** [comment]
I think just making `reflect-metadata` optional dependency would fine in that case.

**Comment by kaorun343** [comment]
OK.

**Comment by paerallax** [comment]
If this gets merged, and the decorators from `vue-property-decorator` aren't used, will they be treeshaken away?

**Comment by l5x** [comment]
@paerallax good point. Something like this would be nice

```ts
import { Compontent, Watch } from 'vue-class-component'

@Component
class MyComp extends Vue {
  @Watch('child')
  onChildChanged(val: string, oldVal: string) { }
}
```

In this case `index.ts` should not import `Watch` [on line 6](https://github.com/vuejs/vue-class-component/pull/213/files#diff-f41e9d04a45c83f3b6f6e630f10117feR6)

**Comment by kaorun343** [comment]
I will add more commits after February due to my research at university, thanks.

**Comment by kaorun343** [comment]
Done.

Review this PR, please.

**Comment by kaorun343** [comment]
@ktsn 
Could you review this PR?

**Pull request closed without merging**
