### PR TITLE
Migrate to TypeScript

### PR DESCRIPTION
**Pull request by ktsn**
I think it would be better to write the code of this project in TypeScript due to high affinity with user land TypeScript code.
We don't have to write declaration files since TS compiler will generate them automatically.

In this PR, I've rewrite `index.js` to `index.ts` with adding type annotations, also replace `Component.name` with `Component._componentTag`. (In my understood, there is no `Component.name` in Vue 2.0?)

How would you feel about this?

### CODE REVIEW

**Comment by kaorun343** [comment]
I think, there's less benefits for TypeScript users to write `internalHooks` such as `data`, `render` and lifecycle hooks. It's because these functions cannot be accessed from the Vue instance and we cannot know the arguments of `render` when defining it in the class syntax.

So, how about removing `internalHooks`?

**Comment by ktsn** [comment]
Then, how should we define the lifecycle hooks and the render hook?
I feel it is a little wired to define these hooks in decorator options, and unfortunately that change will be breaking change.

**Comment by ktsn** [comment]
Also rewrote test code.

**Comment by kaorun343** [comment]
This is my opinion that what we should write in a class syntax is only the properties / methods of an instance. So, it's a little weird, I think, that this library allow us to write like this below.

```typescript
@Component({})
class App extends Vue {
  mounted() {
    return true
  }

  render() {
    return
  }

  instanceMethod() {
    const bool = this.mounted()
  }
}
```

Of course, this change will be a breaking change. However, it seems that the cost of fixing code is not hard.

**Comment by ktsn** [comment]
Can we move on to separated issue for this discussion?
It seems not to essentially related to this PR.

**Comment by kaorun343** [comment]
I see.

**Comment by yyx990803** [comment]
The compiled decorator would still work for Babel, right?

**Comment by ktsn** [comment]
Yes, it should work with [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) on Babel 6 because TypeScript's decorator is the stage 1 decorator implementation.

**Comment by yyx990803** [comment]
@ktsn in that case, can we mention that in the README so the usage is clear?

**Comment by ktsn** [comment]
@yyx990803 I've updated readme to mention about decorators.

And I noticed I missed example code, also updated it.

**Pull request merged**
